
//temporary data
export const userRows = [
  {
    id: 1,
    username: "Vineeth",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    status: "active",
    email: "Vineeth@gmail.com",
    age: 35,
  },
  {
    id: 2,
    username: "Vineeth",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "Vineeth@gmail.com",
    status: "Out of Hotel",
    age: 42,
  },
  {
    id: 3,
    username: "Vineeth",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "Vineeth@gmail.com",
    status: "Pre-Booking",
    age: 45,
  },
  {
    id: 4,
    username: "Vineeth",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "Vineeth@gmail.com",
    status: "active",
    age: 16,
  },
  {
    id: 5,
    username: "Vineeth",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "Vineeth@gmail.com",
    status: "Out of Hotel",
    age: 22,
  },
  {
    id: 6,
    username: "Vineeth",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "Vineeth@gmail.com",
    status: "active",
    age: 15,
  },
  {
    id: 7,
    username: "Vineeth",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "Vineeth@gmail.com",
    status: "Out of Hotel",
    age: 44,
  },
  {
    id: 8,
    username: "Vineeth",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "Vineeth@gmail.com",
    status: "active",
    age: 36,
  },
  {
    id: 9,
    username: "Vineeth",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "Vineeth@gmail.com",
    status: "Pre-Booking",
    age: 65,
  },
  {
    id: 10,
    username: "Vineeth",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "Vineeth@gmail.com",
    status: "active",
    age: 65,
  },
];
